### ISSUE TITLE
When trying to install the Quotes plugin from Plugins -> Add New.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing-quotes#67]
```
 Warning: Undefined array key "search" in /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php on line 299

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php:302 Stack trace: #0 /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php(302): array_merge(NULL, Array) #1 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(289): wpinv_settings_sanitize(Array) #2 /Users/laranz/Sites/geo/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array) #3 /Users/laranz/Sites/geo/wp-includes/formatting.php(4906): apply_filters('sanitize_option...', Array, 'wpinv_settings', Array) #4 /Users/laranz/Sites/geo/wp-includes/option.php(369): sanitize_option('wpinv_settings', Array) #5 /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php(84): update_option('wpinv_settings', Array) #6 /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php(116): wpinv_update_options(Array) #7 /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/admin-pages.php(253): wpinv_update_option('quote_history_p...', 113) #8 /Users/laranz/Sites/geo/wp-content/plugins/invoicing-quotes/admin/class-wpinv-quotes-admin.php(62): wpinv_create_page('your-quotes', 'quote_history_p...', 'Your Quotes', '\r\n ...') #9 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(287): WPInv_Quotes_Admin->maybe_create_initial_pages('') #10 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #11 /Users/laranz/Sites/geo/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #12 /Users/laranz/Sites/geo/wp-admin/admin.php(175): do_action('admin_init') #13 /Users/laranz/Sites/geo/wp-admin/plugins.php(10): require_once('/Users/laranz/S...') #14 /Users/laranz/.composer/vendor/laravel/valet/server.php(214): require('/Users/laranz/S...') #15 {main} thrown in /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/admin/register-settings.php on line 302
```

After refreshing the error gone.

**Comment by picocodes** [comment]
Fixed thanks @laranz
